#!/usr/bin/env bash

# Development script with file watching
# Usage: project dev [--db-url <url>] [--port <port>] 
# where "project" is the apptools dispatcher available when AppTools has been installed


# Setup cleanup on exit
cleanup() {
	[[ -n "${WATCHEXEC_PID:-}" ]] && kill "$WATCHEXEC_PID" 2>/dev/null
	exit 0
}
trap cleanup SIGINT SIGTERM

# Watch for changes using watchexec with restart and bell flags
watchexec -r -w source/ -- \
	bash -c '
		"$APPTOOLS_DIR_PATH/build" --dest=./dist --db-reset-ok "$@" &&
		"$APPTOOLS_DIR_PATH/start" "$@"
	' bash "$@" &
WATCHEXEC_PID=$!

wait "$WATCHEXEC_PID"
